### PR TITLE
Avoid deprecation warnings on Rails 5 for accessing MIME types via constants

### PR DESCRIPTION
**Pull request by micapam**
I've noticed that on my Rails 5 project I get deprecation warnings that I can trace to csv_shaper. 

This PR will fix those deprecation warnings.

### CODE REVIEW

**Comment by micapam** [comment]
Hmm - I don't think that build failure has anything to do with my change :/

**Comment by paulspringett** [comment]
@micapam yeah, looks like Ruby 1.9.3 which is failing for unrelated reasons. Thanks for the PR!

**Comment by edariedl** [comment]
Hi @paulspringett, when do you plan to release new version of the gem with code from this pull request?

**Comment by paulspringett** [comment]
@edariedl version 1.3.0 released here: https://rubygems.org/gems/csv_shaper/versions/1.3.0

**Comment by edariedl** [comment]
Amazing, thank you :)

**Pull request merged**
